env:
  global:
  - secure: a8LHk0wmhHRHTQrvk3l6I7LqvC8s40A8Wfak6tMjqcO+XQqygF8PperQPYHrpnTouHlYDASGK1yikWeXQdQ1EpFQ7vbAeSuSjRrCRla5nVJlwxQ23IUEK9gczLQnZKGifEoKUP9+QeZSO0JTFursvVEE0yBRBkGG60AyOqfaKCAuJjmbmHF2vIXMeNq1i9rN8J6aAnHcIk2Jsu9YhK3OVMQpt3SEP6d/VDZWqQf96P397lHtBdfijhlJXDxTuxk9L/Y55sZNS0IoxERhSMevZ0gYT1w2W/0kFNKc2h4+2h5Bu67esiBB6WKbrQS9XHi9pswi9L5km7jZKNHAyMs/0bE2pGH6VX1sM7Q267JkOKrL4ulu9q9i5Bzd4i6h90f180L6uzk34yuYXs13PdmmsA/sjLap17P7TYCH9smScrUcAqW007ChLH2+XQjYabi11Cpa4rhOb2TmJ0R3eZdGqHAsHpVLnGuDzDCMXyh2IWf+3qZmftfqKY12n7uSvLvwhnHWF1EE1AO1geOjIV3rkfdTunW5b46cPday8a/7egg+XkAe/dn+tRq/iTZDuY3s+YCrcmqUeFuRyQ/36/dbgRvM2xi3qjsoU6HOgoWTwjVdY0G5efrliWC2UWooCOCkcubmngx4Pne1f+wB9GqqNzli4dKx7xsFCEPudYHalYA=
  - secure: ssonYOX/P6v0EnGdbVGOsrIlyyS1L+ohj9155bNsTl7E+FWFhYSPC74fsbQScDZNCDjq2BQj8066qn+JTxF7TaGPkAj1q6hfdhcmoFEXKX4YnlRs7qou5e6PIlhOQm9aTcR0go8BQ+B17IN9IqGBsAGeV3hgoll4pTHQK0X3zOQennDSeFIWKLf5J9x5ckK3ZvwPSF+XQDzbuCK8b0CGx+QXWpqNzUofZ5gwW26IUYtTO+neUY+d0T5SYrGtDYFSY4V1C7rKgZqaXZs+ZntD7nr/CAokTkDk7pbPHYNQTWO/p5y0bycGp8AwbneCzrn60RGimgSOY1tMMICn9xhbas/uzJxYp603Kd151ncgnYzywjxbz1UPBW7KHF9IegM4vPiyFwBXQuaYypzE67CKM6yuAow+NMdA4bhFcfY1vGE++dC92eJUuP1S+K2+RcdW2INlZ0UzfTiOPDdFsD3r+erKUD5bP41F6We1h4mZR0luPCPL//D3yquT0bsi2+6tPj0lGN1RDUu0znYDpJJioxk7nKR1vEo4dS6Q7qZB7F41iRIwpDVhxOnPrDvNkFRUda1OJISg+5aDt5OeE1Tv5EXiyknxGHyFUdYvp5D5RL6IUL974on/xtSN+EUrQf4retx1J0GyBSVuiSbiNz8mRnFHDfGmbJoOQpNqOa2dqLU=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: Udq+ykA5sG8Gah/rNX63ybHHMCA+65Bg6Hhq7oBxaTE4C15RsWSBRNgyhmp9YS75FRKp1WdjLuLSg6WUMqPVp66sOQWScN6jdm4lz+VZ0eDEQiqwpTvfAU3kkRgYB4/9qBPx5YaeRduAo21yx7RE4taH9wM5zuEa6YJnQM24BPbs/kSfLqQ5jhaGjuXJvu8stmUNQlcPRYF6u7qbHS1v+k3tMwLwIuIG6GqlpcKUaK42PgHdV0IEl2NN43i0VKXtasFFGo7x5NbZI6wGQ9YGuIoiW4sRfwU0rNWBP4gvG8LU/fVu3nw87mc01pfu5KkiN21kWqYAAdBGTSwsr7J8CGtd16u6VWBFJ/lAwRmwafZzdRB1StHJBAEAxOzwb6TU3/AQKIaRVjm5UlUyaO2q/sVQeImpkFU3BCKLyGsnZlgMR2xJIMkKui6CtM8oUz/N6uotpBVwOl9hA+FKXblvkMz2nes3tSiWlO0UbTX8c2saE8rSjhBPwfqIVAf9UitIcOG4nI5epnTJlPJ77U7E1LoEHKdKhNr2Vm6yT+O1c4BEKwso/359+9GArry0rhQSD/411tOOwXG70Iu2jaxgBCCumqUgnsdfav5RUOqsqXOvpZqzP79eDRIIMhTc2DLKxDtbOcbxykZKGOSD4rVapVYsZgeME0S3vpwA2z8g42M=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: RBlL6HVcQCi9AqGvUPbn23CJ2/tJpYxbQdjAQx36qDBiO9PA86bzRz7FSIL/tMhNwVOfUQTTFwtmvQU7aoaaxPL39KZ5I+NIZZW96UfN87XTfGosA3lcHk02JA2vT+0d/RMriBUdMsH6fiYtmKwGq58bPB4sRSDIEWpSsuU9kbD0pPP5NF802Ee3S/NNPjpIb4M89IPph3BZGqiGIlJwGQT+1oJ5PXEBNnGKpZ38j/0/Hhc7rUNi57Q5/KCkcqDM7Y/EuBSANsTTrid8LckMRTHmiceAEbl/d7TuCVOz3TLzQNjVr3CoZGASQlkK2nDdtbi/jneMAoX/YU6/JJ3XEvdYeOa4Rzm/+zXDUUmGvfc+56VG+zodtVQUDFIWAibaqBH4Q99he6/cSJKpmnw6A0Yfmg1336wSg20A7huysyPa9XaGc62N6ac2kmITRni5Z4tcBj/K1wCGcjT4cfgEtMMMC3ij3mkOPOJgNMGbI9zHVFRSuolIBB74iCVv/EOHvXno1FBg9sv3IVRVvz3ohDzck0UqW6enWD5H3a5+Ctw8NfPucDWJrw8E0JYXQF/lo67r7e4ExN9OOXpY9/h4Y9WebxXRQA0Jp1D0Z8lxQrzskVsnFjmT3mNJE/F2VqUUSxzRo9WAMDhZIp0Qfs7hkbMEWKlXJMNJ6Z/yBgShrkU=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
