env:
  global:
  - secure: HPp7vd0qJ/QnSyyJvhi/W3F1TiJArrRzz2GVnsBYT3m36QxHhdrpX1USsAHTkpABj/p205wuUN0pxhLCzdMjMi7mBKD6f54sAsP9TqgkdLxYB5StJsTzput28ctf4B1e9A/vuu87Nk4YyYl4+ZiMeg6Ytl6Zit4Tq+V4AmaugkKT9E+ddsVODGry2mGJ1zv/55dl/Ofx7tsQpc8amYQw6eZUYSx9A2e2zaV9IB1q7EC+39x70EeUbn6AXr0WNfFLdwzGxW22aep/6HwtH+yPoEi1kdw7yyiyELS01u9A+TmdddiFYPxSSW03YUzPp5yxUKYU/1N1EHPEBSHpHaCmM029wKxl+gT+JLr66PKwHjCefyTBNfbMUpSx/MFPFau1aPNBGO5GeSFqOS18lTJZSkl+sXsQVCWdgq3Cuf1e7BhrHY+t6ZSTYIAl6jrDuiOQONpELsftXxZsxPVlogHsAB2fsYFTJ7exhsIBTVNF0n/c0FJlVBkm2dku1bk10eJC7RC8JEthw6KJxDveFdpJJoG5hYwIuAG63dbcU6Pjg81s1YSA6VT2vSps/wcMJrLonCha1Woc1rvfcf4SWGkPKJlENo8tv/vSoenVGesra/RDpKH9FALWqA4XbHOPuvXTHJBUXn8qI6Is+wFCnLwh/oC86OfTjtqZHRbRB/jNRi4=
  - secure: cy+O5fFbA8hktx39e5DgWFK4vwnWB3MvZxwu4chjuK/2SDNB5R120u7i8Z8PGrsuC2WerAHMwIpNU4fMNXnsLhpq8H04UL6wLApbC0YI3EUsljX8VUzAJQ5X2+2FsWOHKwNFbBbFeC4P/wnPs/9766CHOVUForZQuu2IAUhzuVNXdMbQQ/YNl6HNojIzgBsodLKJ+E2yU5izMz9nXFRnUhFV/63UBwJUa88JTUd9MpnAeTycfW3D/1W4T4M774OcDkoBv4TCf00d/Xl3Rn0M6hDGJG024G+y0TEBNkx2DpRhQPY8zXlx4zLHuO6tydQQQT5wi3zCNEBi8PlZKEEPQhOuLuAUx7aKgCmOEhA3dWJ8lfZvdGr7oKDtm223Mc07CLnMzGgOtKUH3G8a6yQkKELGtIVtqEEV+5AYvpwn+4b6/kH6sygEZZ+yP4+gcRX0sWpgI8MDdr0G9z+ZKYIsTtrvOYgTZkw4kdammbUDalP5p1c7e0AU/Jn7oeCt6W30pEWoEdTBldLQWo4jAP2xmGQKS+R+4eawrM7ye+lut6CBg6G3v9mO3GZLHSaRSLphwheGOt98Ta6Wo7blwzTaw4ncGC9ljy+Adojc+9KdCM9gJlXMIK0q7pHkF4TBGDGNuV3KeGZLiZ5BdnHhwvizZFHZ0/5fCHhVShCQPeAGtoE=

services:
- docker

addons:
  sonarcloud:
    organization: departement-loire-atlantiqu-1
    token:
      secure: Udq+ykA5sG8Gah/rNX63ybHHMCA+65Bg6Hhq7oBxaTE4C15RsWSBRNgyhmp9YS75FRKp1WdjLuLSg6WUMqPVp66sOQWScN6jdm4lz+VZ0eDEQiqwpTvfAU3kkRgYB4/9qBPx5YaeRduAo21yx7RE4taH9wM5zuEa6YJnQM24BPbs/kSfLqQ5jhaGjuXJvu8stmUNQlcPRYF6u7qbHS1v+k3tMwLwIuIG6GqlpcKUaK42PgHdV0IEl2NN43i0VKXtasFFGo7x5NbZI6wGQ9YGuIoiW4sRfwU0rNWBP4gvG8LU/fVu3nw87mc01pfu5KkiN21kWqYAAdBGTSwsr7J8CGtd16u6VWBFJ/lAwRmwafZzdRB1StHJBAEAxOzwb6TU3/AQKIaRVjm5UlUyaO2q/sVQeImpkFU3BCKLyGsnZlgMR2xJIMkKui6CtM8oUz/N6uotpBVwOl9hA+FKXblvkMz2nes3tSiWlO0UbTX8c2saE8rSjhBPwfqIVAf9UitIcOG4nI5epnTJlPJ77U7E1LoEHKdKhNr2Vm6yT+O1c4BEKwso/359+9GArry0rhQSD/411tOOwXG70Iu2jaxgBCCumqUgnsdfav5RUOqsqXOvpZqzP79eDRIIMhTc2DLKxDtbOcbxykZKGOSD4rVapVYsZgeME0S3vpwA2z8g42M=

before_script:
- echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
- docker pull asfram/jplatformbuild

script:
- docker run -v ${TRAVIS_BUILD_DIR}:/root/source --name buildimage -t asfram/jplatformbuild
- docker cp buildimage:/root/dist .
- export CODE_VERSION=`git describe`
- sonar-scanner -Dsonar.projectVersion=$CODE_VERSION

deploy:
  provider: releases
  api_key:
    secure: RBlL6HVcQCi9AqGvUPbn23CJ2/tJpYxbQdjAQx36qDBiO9PA86bzRz7FSIL/tMhNwVOfUQTTFwtmvQU7aoaaxPL39KZ5I+NIZZW96UfN87XTfGosA3lcHk02JA2vT+0d/RMriBUdMsH6fiYtmKwGq58bPB4sRSDIEWpSsuU9kbD0pPP5NF802Ee3S/NNPjpIb4M89IPph3BZGqiGIlJwGQT+1oJ5PXEBNnGKpZ38j/0/Hhc7rUNi57Q5/KCkcqDM7Y/EuBSANsTTrid8LckMRTHmiceAEbl/d7TuCVOz3TLzQNjVr3CoZGASQlkK2nDdtbi/jneMAoX/YU6/JJ3XEvdYeOa4Rzm/+zXDUUmGvfc+56VG+zodtVQUDFIWAibaqBH4Q99he6/cSJKpmnw6A0Yfmg1336wSg20A7huysyPa9XaGc62N6ac2kmITRni5Z4tcBj/K1wCGcjT4cfgEtMMMC3ij3mkOPOJgNMGbI9zHVFRSuolIBB74iCVv/EOHvXno1FBg9sv3IVRVvz3ohDzck0UqW6enWD5H3a5+Ctw8NfPucDWJrw8E0JYXQF/lo67r7e4ExN9OOXpY9/h4Y9WebxXRQA0Jp1D0Z8lxQrzskVsnFjmT3mNJE/F2VqUUSxzRo9WAMDhZIp0Qfs7hkbMEWKlXJMNJ6Z/yBgShrkU=
  file_glob: true
  file: "${TRAVIS_BUILD_DIR}/dist/*.zip"
  skip_cleanup: true
  on:
    tags: true
